/*
 * Copyright (C) 2020, Xilinx Inc - All rights reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may
 * not use this file except in compliance with the License. A copy of the
 * License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
//
// ==============================================================

// control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of A
//        bit 31~0 - A[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of C
//        bit 31~0 - C[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of args_REPS
//        bit 31~0 - args_REPS[31:0] (Read/Write)
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//in_r 	0x10
//out_r	0x1c
//n	0x28
//base_address 0x1870000

#define XSORT_CONTROL_ADDR_AP_CTRL        0x00
#define XSORT_CONTROL_ADDR_GIE            0x04
#define XSORT_CONTROL_ADDR_IER            0x08
#define XSORT_CONTROL_ADDR_ISR            0x0c
#define XSORT_CONTROL_ADDR_A_DATA         0x10
#define XSORT_CONTROL_BITS_A_DATA         32
#define XSORT_CONTROL_ADDR_OUTPUT_R_DATA  0x1c
#define XSORT_CONTROL_BITS_OUTPUT_R_DATA  32
#define XSORT_CONTROL_ADDR_REPEAT_R_DATA  0x20
#define XSORT_CONTROL_BITS_REPEAT_R_DATA  32

