set SDA_PATH [pwd]
read_verilog -sv [glob \
$SDA_PATH/src/hdl/dpuv3_shell/dpdpuv3_wrapper.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/inc/*.vh \
$SDA_PATH/../../ml_ip/cnnv3/rtl/dpdpuv3_dbg_rst.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/dpdpuv3_dma_bridge.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/dpdpuv3_top.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/dpdpuv3_core.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/common/axis_sync_fifo.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/common/ram_s2p1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/common/axi_rs.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/flowctrl/dpdpuv3_flowctrl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/fu_arbconf/dpdpuv3_wtvld_gen.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/fu_arbconf/dpdpuv3_buf_rreq.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/fu_arbconf/dpdpuv3_datashifter.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/fu_arbconf/dpdpuv3_rdgen_datareorg.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_prof_collect.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_ram_128bx8bx1k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_ram_512bx8bx1k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_fifo_full.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_axiw_req_spcltv_vld.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_ram_spcltv_full.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_spcltv_en.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_rd_req_spcltv_full.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_wr_req_spcltv_full.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_req_ctl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_wreq_ctl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_wt_last_empt.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_ctl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_rd_buf.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_wr_buf.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/org_dma/rtl/fu_xchn/dpdpuv3_fu_x_top.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_scheduler.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_dependence.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_fetch.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_distribute.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_cmdctrl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/scheduler/dpdpuv3_profiler.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/datamover/dpdpuv3_dm_axchnl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/datamover/dpdpuv3_dm_rchnl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/datamover/dpdpuv3_dm_wbchnl.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/datamover/dpdpuv3_dm_load.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/datamover/dpdpuv3_dm_save.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_calc.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_calc_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_reader.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_reader_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_relu.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/element_wise/dpdpuv3_ele_com_top.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_max_calc.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_avg_1_2_4_6_9_calc.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_avg_1_2_4_6_9_calc_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_calc.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_calc_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_pad_cnt.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_pad_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_pad.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_pad_com.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_pad_mask_code_gen.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_reader.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_request_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/pool/dpdpuv3_pool_com_top.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_accu_calc.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_ins_parser.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_com.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_core.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_writer.sv \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_misc_writer_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/misc/dpdpuv3_alignedsplit.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_dram_fifo.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_bram_1r1w1c_model.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_128bx8k_1r1w1c_model.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_2048bx8k_1r1w1c_model.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_18bx8k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_2048bx8k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_1bx2k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_8bx2k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_bank_r64bw64bx2k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_bank_grp.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkrd/dpdpuv3_arb_rd_req_chn_spcltv_full.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkrd/dpdpuv3_arb_rd_seperate_req_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkrd/dpdpuv3_arb_rd_req_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkrd/dpdpuv3_arb_rd_arb.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkrd/dpdpuv3_arb_rd_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_seperate_req_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_data_pipeline.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_addr_pipeline.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_req_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_arb.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/arb/bkwr/dpdpuv3_arb_wr_chn.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_img.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ppe.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_128bx8k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_ram_128bx4k_1r1w1c.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/ultraram_simple_dual_port_64b_80k.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/buf/dpdpuv3_buf_weight_simple.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_cfg_case_mux_1h_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_cfg_case_mux_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_regs_en_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/dpdpuv3_conv_writer.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/dpdpuv3_conv_top_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_cfg_mux_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_dec_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_regs_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_dsp_cascade.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_calc_part.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_dsp_block.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_dsp_chain.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_f2l_2_1.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_pingpong_buffer.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_shift_regs_.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_dsp_acc_adder.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/pe_array/dpdpuv3_conv_dsp_wide_acc.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/post_calc/dpdpuv3_addbias.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/post_calc/dpdpuv3_non_linear.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/post_calc/dpdpuv3_split2one.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/post_calc/dpdpuv3_fetch_res.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/image_padding/dpdpuv3_conv_pad_core.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_core/image_padding/dpdpuv3_img_mask.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/dpdpuv3_conv_top_com.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/dpdpuv3_conv_parser.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/pad_code_gen/dpdpuv3_conv_paddingmask.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/pad_code_gen/dpdpuv3_img_pad_mask_code_gen.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_img_reader.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_wgt_reader.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_conv_reader.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_param_reader.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_bias_reader.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_img_addr_gen.v \
$SDA_PATH/../../ml_ip/cnnv3/rtl/conv/conv_common/reader/dpdpuv3_wgt_trig_gen.v \
]
