
####################################################################################
# Generated by Vivado 2022.1 built on 'Mon Apr 18 15:47:01 MDT 2022' by 'xbuild'
# Command Used: write_xdc -force -exclude_timing ./vitis_design_wrapper_physical_golden.xdc
####################################################################################


####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_3_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_ps_e_0.xdc'
####################################################################################

##############################PS XDC#########################################
############################################################################
##
##  Xilinx, Inc. 2006            www.xilinx.com
############################################################################
##  File name :       psu_constraints.xdc
##
##  Details :     Constraints file
##                    FPGA family:       zynq
##                    FPGA:              PROD-2
##                    Device Size:       xczu9eg
##                    Package:           ffvb1156
##                    Speedgrade:        -2
##
##
############################################################################
############################################################################
############################################################################
# Clock constraints                                                        #
############################################################################



current_instance vitis_design_i/ps_e/inst
set_property DONT_TOUCH true [get_cells PS8_i]


####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_6_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_6_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_6_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_5_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_5_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_5_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_4_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_4_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_4_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_3_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_3_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_axi_intc_0_0.xdc'
####################################################################################

# file: vitis_design_axi_intc_0_0.xdc
# (c) Copyright 1984 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.


####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_2_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_2_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_2_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_1_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_1_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_1_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_0_0.xdc'
####################################################################################


# file: vitis_design_proc_sys_reset_0_0.xdc
# (c) Copyright 2009 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.



####################################################################################
# Constraints from file : 'vitis_design_proc_sys_reset_0_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'vitis_design_clk_wiz_0_0.xdc'
####################################################################################


# file: vitis_design_clk_wiz_0_0.xdc
#
# (c) Copyright 2008 - 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.
#

# Input clock periods. These duplicate the values entered for the
# input clocks. You can use these to time your system. If required
# commented constraints can be used in the top level xdc
#----------------------------------------------------------------
# Connect to input port when clock capable pin is selected for input


current_instance -quiet
current_instance vitis_design_i/clk_wiz_0/inst
set_property PHASESHIFT_MODE LATENCY [get_cells -hierarchical *adv*]


####################################################################################
# Constraints from file : 'vitis_design_clk_wiz_0_0_board.xdc'
####################################################################################

#--------------------Physical Constraints-----------------



####################################################################################
# Constraints from file : 'pblock.xdc'
####################################################################################

current_instance -quiet

####################################################################################
# Constraints from file : 'vitis_design_axi_intc_0_0_clocks.xdc'
####################################################################################

# file: vitis_design_axi_intc_0_0_clocks.xdc
# (c) Copyright 2013 Xilinx, Inc. All rights reserved.
#
# This file contains confidential and proprietary information
# of Xilinx, Inc. and is protected under U.S. and
# international copyright and other intellectual property
# laws.
#
# DISCLAIMER
# This disclaimer is not a license and does not grant any
# rights to the materials distributed herewith. Except as
# otherwise provided in a valid license issued to you by
# Xilinx, and to the maximum extent permitted by applicable
# law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
# WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
# AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
# BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
# INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
# (2) Xilinx shall not be liable (whether in contract or tort,
# including negligence, or under any other theory of
# liability) for any loss or damage of any kind or nature
# related to, arising under or in connection with these
# materials, including for any direct, or any indirect,
# special, incidental, or consequential loss or damage
# (including loss of data, profits, goodwill, or any type of
# loss or damage suffered as a result of any action brought
# by a third party) even if such damage or loss was
# reasonably foreseeable or Xilinx had been advised of the
# possibility of the same.
#
# CRITICAL APPLICATIONS
# Xilinx products are not designed or intended to be fail-
# safe, or for use in any application requiring fail-safe
# performance, such as life-support or safety devices or
# systems, Class III medical devices, nuclear facilities,
# applications related to the deployment of airbags, or any
# other applications that could lead to death, personal
# injury, or severe property or environmental damage
# (individually and collectively, "Critical
# Applications"). Customer assumes the sole risk and
# liability of any use of Xilinx products in Critical
# Applications, subject only to applicable laws and
# regulations governing limitations on product liability.
#
# THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
# PART OF THIS FILE AT ALL TIMES.


####################################################################################
# Constraints from file : 'vitis_design_axi_register_slice_0_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_axi_register_slice_0_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_us_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_dwidth_converter Component "vitis_design_auto_us_0"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)


####################################################################################
# Constraints from file : 'vitis_design_m01_regslice_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m01_regslice_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_cc_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_clock_converter Component "vitis_design_auto_cc_0"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)





####################################################################################
# Constraints from file : 'vitis_design_m02_regslice_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m02_regslice_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_cc_1_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_clock_converter Component "vitis_design_auto_cc_1"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)





####################################################################################
# Constraints from file : 'vitis_design_m03_regslice_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m03_regslice_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_cc_2_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_clock_converter Component "vitis_design_auto_cc_2"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)





####################################################################################
# Constraints from file : 'timing_clocks.xdc'
####################################################################################

##########################
# constrains for DDR-DSP #
##########################






####################################################################################
# Constraints from file : 'timing_clocks.xdc'
####################################################################################

##########################
# constrains for DDR-DSP #
##########################






####################################################################################
# Constraints from file : 'vitis_design_s00_regslice_4_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s00_regslice_4"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_us_df_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_dwidth_converter Component "vitis_design_auto_us_df_0"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)


####################################################################################
# Constraints from file : 'vitis_design_s01_regslice_5_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s01_regslice_5"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_us_df_1_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_dwidth_converter Component "vitis_design_auto_us_df_1"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)


####################################################################################
# Constraints from file : 'vitis_design_m00_data_fifo_4_clocks.xdc'
####################################################################################



current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HPC0_FPD/m00_couplers/m00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:34 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_m00_regslice_4_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m00_regslice_4"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_regslice_5_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s00_regslice_5"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_data_fifo_5_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s00_couplers/s00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:34 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_s01_regslice_6_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s01_regslice_6"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s01_data_fifo_6_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:34 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_s02_regslice_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s02_regslice_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s02_data_fifo_0_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_s03_regslice_0_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s03_regslice_0"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s03_data_fifo_0_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_m00_data_fifo_5_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/m00_couplers/m00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_m00_regslice_5_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m00_regslice_5"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_regslice_6_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s00_regslice_6"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_data_fifo_6_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s00_couplers/s00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_s01_regslice_7_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s01_regslice_7"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s01_data_fifo_7_clocks.xdc'
####################################################################################





####################################################################################
# Constraints from file : 'vitis_design_m00_data_fifo_6_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/m00_couplers/m00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_m00_regslice_6_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m00_regslice_6"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_regslice_7_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s00_regslice_7"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_s00_data_fifo_7_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s00_couplers/s00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:35 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_s01_regslice_8_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_s01_regslice_8"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'vitis_design_auto_us_df_2_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_dwidth_converter Component "vitis_design_auto_us_df_2"
###############################################################################################################
#
# This component is not configured to perform asynchronous clock-domain-crossing.
# No timing core-level constraints are needed.
# (Synchronous clock-domain-crossings, if any, remain covered by your system-level PERIOD constraints.)


####################################################################################
# Constraints from file : 'vitis_design_m00_data_fifo_7_clocks.xdc'
####################################################################################



current_instance -quiet
current_instance vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/m00_couplers/m00_data_fifo/inst
create_waiver -type METHODOLOGY -id {LUTAR-1} -user "axi_data_fifo" -desc "the pathway is completely within fifo-gen, and that path is present single-clock usage" -tags "1024446" -scope -internal -objects [get_cells -hierarchical -filter (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/reset_gen_cc.rstblk_cc/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space*)] -objects [get_pins -hierarchical * -filter {(NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/CLR) || (NAME=~*gen_fifo.fifo_gen_inst/inst_fifo_gen/gaxi_full_lite.gread_ch.gaxi_pkt_fifo_rd.gaxi_mm_cc_pkt_rd.rd_fifo_free_space_reg*/PRE)}] -timestamp "Thu Jun  9 17:57:36 GMT 2022"


####################################################################################
# Constraints from file : 'vitis_design_m00_regslice_7_clocks.xdc'
####################################################################################

###############################################################################################################
# Core-Level Timing Constraints for axi_register_slice Component "vitis_design_m00_regslice_7"
###############################################################################################################
#
# This component is not configured in a multi-SLR crossing mode.
# No timing core-level constraints are needed.
#
#



####################################################################################
# Constraints from file : 'xpm_cdc_async_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst

# Scoped constraints for xpm_cdc_async_rst


####################################################################################
# Constraints from file : 'xpm_cdc_sync_rst.tcl'
####################################################################################

# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst


# Scoped constraints for xpm_cdc_srst



# User Generated miscellaneous constraints 

current_instance -quiet
set_property LOCK_PINS {I0:A4 I1:A2 I2:A3} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s01_couplers/s01_regslice/inst/ar.ar_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s01_couplers/s01_regslice/inst/ar.ar_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A4 I1:A3 I2:A6 I3:A5} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/aw.aw_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A5 I1:A4 I2:A6} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/aw.aw_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/aw.aw_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/aw.aw_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A4 I1:A3 I2:A5} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/b.b_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A4 I1:A2 I2:A5 I3:A3} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/b.b_pipe/s_ready_i_i_1__0]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[0]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[100]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[101]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[106]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[102]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[103]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[107]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[104]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[105]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[108]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[109]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[110]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[111]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[114]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[115]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[116]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[117]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[118]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[119]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[120]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[121]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[122]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[123]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[126]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[127]_i_2}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[128]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[129]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[12]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[130]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[131]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[132]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[133]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[134]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[135]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[136]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[137]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[138]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[139]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[13]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[140]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[141]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[142]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[143]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[144]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[14]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[15]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[16]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[17]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[18]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[19]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[1]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[20]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[21]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[22]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[23]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[24]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[25]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[26]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[27]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[28]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[29]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[2]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[30]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[31]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[32]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[33]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[34]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[35]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[36]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[37]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[38]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[39]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[3]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[40]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[41]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[42]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[43]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[44]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[45]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[46]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[47]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[48]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[49]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[4]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[50]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[51]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[52]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[53]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[56]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[57]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[5]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[60]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[61]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[64]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[65]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[66]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[67]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[68]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[69]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[6]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[70]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[71]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[74]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[75]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[78]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[79]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[7]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[80]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[81]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[82]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[83]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[84]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[85]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[86]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[87]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[88]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[89]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[8]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[92]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[93]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[94]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[95]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[96]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[97]_i_1}]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[98]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[99]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A1 I2:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_payload_i[9]_i_1}]
set_property LOCK_PINS {I0:A4 I1:A2 I2:A5 I3:A3} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/m_valid_i_i_1__1]
set_property LOCK_PINS {I0:A5 I1:A4 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP1_FPD/s01_couplers/s01_regslice/inst/w.w_pipe/s_ready_i_i_1__1]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_regslice/inst/ar.ar_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A5 I1:A3 I2:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_regslice/inst/ar.ar_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A5 I1:A4} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/m_payload_i[127]_i_1}]
set_property LOCK_PINS {I0:A4 I1:A1 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A5 I1:A4 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/s_ready_i_i_1__0]
set_property LOCK_PINS {I0:A2 I1:A3 I2:A5 I3:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_regslice/inst/ar.ar_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A2 I1:A3 I2:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_regslice/inst/ar.ar_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A4 I1:A5} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_regslice/inst/r.r_pipe/m_payload_i[127]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A3 I2:A5 I3:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_regslice/inst/r.r_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A4 I1:A5 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s02_couplers/s02_regslice/inst/r.r_pipe/s_ready_i_i_1__0]
set_property LOCK_PINS {I0:A1 I1:A2 I2:A4 I3:A3} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_regslice/inst/ar.ar_pipe/s_ready_i_i_2]
set_property LOCK_PINS {I0:A3 I1:A4 I2:A5} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_regslice/inst/ar.ar_pipe/m_valid_i_i_1]
set_property LOCK_PINS {I0:A4 I1:A5} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_regslice/inst/r.r_pipe/m_payload_i[127]_i_1}]
set_property LOCK_PINS {I0:A2 I1:A3 I2:A5 I3:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_regslice/inst/r.r_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A4 I1:A5 I2:A3 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP0_FPD/s03_couplers/s03_regslice/inst/r.r_pipe/s_ready_i_i_1__0]
set_property LOCK_PINS {I0:A6 I1:A5} [get_cells {vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/m_payload_i[63]_i_1__0}]
set_property LOCK_PINS {I0:A3 I1:A4 I2:A5 I3:A2} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A3 I1:A6 I2:A5 I3:A4} [get_cells vitis_design_i/axi_ic_ps_e_S_AXI_HP2_FPD/s01_couplers/s01_regslice/inst/r.r_pipe/s_ready_i_i_1]
set_property LOCK_PINS {I0:A4 I1:A3 I2:A5} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/ar.ar_pipe/m_valid_i_i_1__1]
set_property LOCK_PINS {I0:A3 I1:A2 I2:A4 I3:A5} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/ar.ar_pipe/s_ready_i_i_1__2]
set_property LOCK_PINS {I0:A4 I1:A2 I2:A3} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/b.b_pipe/m_valid_i_i_2]
set_property LOCK_PINS {I0:A5 I1:A2 I2:A4 I3:A3} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/b.b_pipe/s_ready_i_i_1__1]
set_property LOCK_PINS {I0:A6 I1:A4 I2:A5} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/r.r_pipe/m_valid_i_i_1__2]
set_property LOCK_PINS {I0:A6 I1:A3 I2:A5 I3:A4} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/r.r_pipe/s_ready_i_i_1__3]
set_property LOCK_PINS {I0:A4 I1:A5 I2:A6} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/w.w_pipe/m_valid_i_i_1__0]
set_property LOCK_PINS {I0:A3 I1:A4 I2:A6 I3:A5} [get_cells vitis_design_i/interconnect_axilite/m03_couplers/m03_regslice/inst/w.w_pipe/s_ready_i_i_1__0]

# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
