puts "Start to source [info script]"

global DPU_V3_TOP

##### #set ML_SHELL_TOP pfm_top_i/dynamic_region/dpdpuv3_wrapper_1/inst
##### global ML_SHELL_TOP 
##### 
#set ML_SHELL_TOP pfm_top_i/dynamic_region/dpdpuv3_wrapper_1/inst
set all_regs_list [get_cells -hier -filter {PRIMITIVE_TYPE =~ REGISTER.SDR.*}]

#--------------- elew -------------------//
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_width_o_reg[*]/C]         
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_width_o_reg[*]/C]         
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_bank_id_o_reg[*]/C]         
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_bank_id_o_reg[*]/C]         
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_st_addr_o_reg[*]/C]         
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_st_addr_o_reg[*]/C]         
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_jump_o_reg[*]/C]            
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_jump_o_reg[*]/C]            
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_jump_endl_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_jump_endl_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_nonlinear_type_o_reg[*]/C]
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_nonlinear_type_o_reg[*]/C]
#set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_wr_o_reg[*]/C]        
#set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_wr_o_reg[*]/C]        
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_strd_out_o_reg[*]/C]        
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_strd_out_o_reg[*]/C]        
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_strd_off_set_o_reg[*]/C]    
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_wr_strd_off_set_o_reg[*]/C]    
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_width_o_reg[*]/C]         
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_width_o_reg[*]/C]         
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_sets_num_o_reg[*]/C]      
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_sets_num_o_reg[*]/C]      
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_chn_grps_o_reg[*]/C]      
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_chn_grps_o_reg[*]/C]      
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd0_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd0_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd1_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd1_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd2_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd2_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd3_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/ele_reg_calc_shf_rd3_o_reg[*]/C]       
#--------------- pool -------------------//
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_len_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_len_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_bid_out_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_bid_out_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_addr_out_o_reg[*]/C]      
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_addr_out_o_reg[*]/C]      
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_jump_o_reg[*]/C]          
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_jump_o_reg[*]/C]          
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_jump_endl_o_reg[*]/C]     
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_wr_jump_endl_o_reg[*]/C]     
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_calc_pmode_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_calc_pmode_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ker_h_size_o_reg[*]/C]   
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ker_h_size_o_reg[*]/C]   
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ker_w_size_o_reg[*]/C]   
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ker_w_size_o_reg[*]/C]   
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pstride_h_o_reg[*]/C]    
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pstride_h_o_reg[*]/C]    
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pstride_w_o_reg[*]/C]    
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pstride_w_o_reg[*]/C]    
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_r_o_reg[*]/C]            
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_r_o_reg[*]/C]            
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_l_o_reg[*]/C]            
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_l_o_reg[*]/C]            
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_b_o_reg[*]/C]            
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_b_o_reg[*]/C]            
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_t_o_reg[*]/C]            
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_t_o_reg[*]/C]            
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_len_o_reg[*]/C]          
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_len_o_reg[*]/C]          
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ch_grp_o_reg[*]/C]       
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_ch_grp_o_reg[*]/C]       
set_multicycle_path 3 -setup -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pmode_o_reg[*]/C]        
set_multicycle_path 2 -hold -from [get_pins -of $all_regs_list -filter name=~$DPU_V3_TOP/u_misc_com/u_misc_ins_parser/pool_reg_pad_pmode_o_reg[*]/C]        
