name: vitis-ai-lstm

channels:
  - file:///scratch/conda-channel
  - pytorch
  - defaults
  - conda-forge/label/gcc7

dependencies:
  - python=3.6
  - dctc_lstm
  - tf_nndct
  - pytorch_nndct
  - pydot
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - pillow
