name: vitis-ai-tensorflow

channels:
  - file:///scratch/conda-channel
  - pytorch
  - defaults
  - conda-forge/label/gcc7
  - conda-forge

dependencies:
  - python=3.6
  - vai_q_tensorflow_gpu
  - keras
  - pydot
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - pillow
  - vaic
  - xip
  - dpuv1-rt
  - dpuv1-rt-ext
  - ddump
  - vart
  - rt-engine
