name: vitis-ai-pytorch

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python=3.6
  - pytorch_nndct
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - vaic
