export BOARD = versal-vck190-reva-x-ebm-01-reva
export CORE = psv_cortexa72_0
CWD = $(shell readlink -f .)
BUILD_DIR = $(CWD)/petalinux

all:
	$(MAKE) -C $(BUILD_DIR) all

clean:
	$(MAKE) -C $(BUILD_DIR) clean
