## Copyright 2020 Xilinx Inc.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

#--------------------------------------------------------------------------------------------
# Please choose one of the following PYTHON_CFG value for python support package
# This configuration is invalid when using sdk.sh
#--------------------------------------------------------------------------------------------
PYTHON_CFG = yes
#PYTHON_CFG = no

#--------------------------------------------------------------------------------------------
# Please choose one of the following AOL_PATH values and configure XRT or Linux
#--------------------------------------------------------------------------------------------
AOL_PATH=./src/aol/xrt/
#AOL_PATH=./src/aol/linux/

#--------------------------------------------------------------------------------------------
# Please choose one of the following CFLAGS values and configure UltraScale+ or Zynq 7000
# 1. for sdk.sh ----------------------------> CFLAGS += -O2 -DUSE_ARM_NEON
# 2. for gcc on arm64 target board ---------> CFLAGS += -O2 -DUSE_ARM_NEON
# 3. for gcc on arm32 target board ---------> CFLAGS += -O2 -mfloat-abi=hard -mfpu=neon -ffast-math -DUSE_ARM_NEON
# 4. for aarch64-linux-gnu -----------------> CFLAGS += -O2 -mcpu=cortex-a53 -DUSE_ARM_NEON
# 5. for arm-linux-gnueabihf ---------------> CFLAGS += -O2 -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=neon -ffast-math -DUSE_ARM_NEON
#--------------------------------------------------------------------------------------------
CFLAGS += -O2 -DUSE_ARM_NEON
#CFLAGS += -O2 -DUSE_ARM_NEON
#CFLAGS += -O2 -mfloat-abi=hard -mfpu=neon -ffast-math -DUSE_ARM_NEON
#CFLAGS += -O2 -mcpu=cortex-a53 -DUSE_ARM_NEON
#CFLAGS += -O2 -mcpu=cortex-a9 -mfloat-abi=hard -mfpu=neon -ffast-math -DUSE_ARM_NEON
