name: base

channels:
  - conda-forge

dependencies:
  - python=3.8
  - vaic
  - xcompiler
  - vart
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - pandas
  - matplotlib
  - pip
  - pip:
    - ck
    - orderedset
    - opencv-contrib-python
