name: vitis-ai-tensorflow2

channels:
  - conda-forge

dependencies:
  - python=3.8
  - vaic
  - xnnc
  - xcompiler
  - vart
  - rt-engine
  - vai_optimizer_tensorflow2_rocm 
  - vai_q_tensorflow2_rocm
