name: vitis-ai-tensorflow2

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - vai_q_tensorflow2
  - pydot
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - pillow
  - vaic
  - vart
  - rt-engine