name: vitis-ai-pytorch

channels:
  - pytorch
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - pytorch_nndct
  - vaic
  - dpuv3-pycompiler
  - xnnc
  - xcompiler
  - vart
  - vai_utf
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - pip
  - pip:
    - ck
    - orderedset
    - opencv-contrib-python

