name: vitis-ai-pytorch

channels:
  - pytorch
  - conda-forge
  - prometeia

dependencies:
  - python=3.8
  - pytorch_nndct
  - libprotobuf=3.21.3
  - vaic
  - xcompiler
  - vart
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
  - pip
  - pip:
    - ck
    - orderedset
    - opencv-contrib-python

