// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.2
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Core_Process (
        ap_clk,
        ap_rst,
        imgblock_0_0_V_read,
        imgblock_0_1_V_read,
        imgblock_0_2_V_read,
        imgblock_0_3_V_read,
        imgblock_0_4_V_read,
        imgblock_0_5_V_read,
        imgblock_0_6_V_read,
        imgblock_0_7_V_read,
        imgblock_0_8_V_read,
        imgblock_0_9_V_read,
        imgblock_1_0_V_read,
        imgblock_1_1_V_read,
        imgblock_1_2_V_read,
        imgblock_1_3_V_read,
        imgblock_1_4_V_read,
        imgblock_1_5_V_read,
        imgblock_1_6_V_read,
        imgblock_1_7_V_read,
        imgblock_1_8_V_read,
        imgblock_1_9_V_read,
        imgblock_2_0_V_read,
        imgblock_2_1_V_read,
        imgblock_2_2_V_read,
        imgblock_2_3_V_read,
        imgblock_2_4_V_read,
        imgblock_2_5_V_read,
        imgblock_2_6_V_read,
        imgblock_2_7_V_read,
        imgblock_2_8_V_read,
        imgblock_2_9_V_read,
        imgblock_3_0_V_read,
        imgblock_3_1_V_read,
        imgblock_3_2_V_read,
        imgblock_3_3_V_read,
        imgblock_3_4_V_read,
        imgblock_3_5_V_read,
        imgblock_3_6_V_read,
        imgblock_3_7_V_read,
        imgblock_3_8_V_read,
        imgblock_3_9_V_read,
        imgblock_4_0_V_read,
        imgblock_4_1_V_read,
        imgblock_4_2_V_read,
        imgblock_4_3_V_read,
        imgblock_4_4_V_read,
        imgblock_4_5_V_read,
        imgblock_4_6_V_read,
        imgblock_4_7_V_read,
        imgblock_4_8_V_read,
        imgblock_4_9_V_read,
        row,
        col,
        loop_r,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [9:0] imgblock_0_0_V_read;
input  [9:0] imgblock_0_1_V_read;
input  [9:0] imgblock_0_2_V_read;
input  [9:0] imgblock_0_3_V_read;
input  [9:0] imgblock_0_4_V_read;
input  [9:0] imgblock_0_5_V_read;
input  [9:0] imgblock_0_6_V_read;
input  [9:0] imgblock_0_7_V_read;
input  [9:0] imgblock_0_8_V_read;
input  [9:0] imgblock_0_9_V_read;
input  [9:0] imgblock_1_0_V_read;
input  [9:0] imgblock_1_1_V_read;
input  [9:0] imgblock_1_2_V_read;
input  [9:0] imgblock_1_3_V_read;
input  [9:0] imgblock_1_4_V_read;
input  [9:0] imgblock_1_5_V_read;
input  [9:0] imgblock_1_6_V_read;
input  [9:0] imgblock_1_7_V_read;
input  [9:0] imgblock_1_8_V_read;
input  [9:0] imgblock_1_9_V_read;
input  [9:0] imgblock_2_0_V_read;
input  [9:0] imgblock_2_1_V_read;
input  [9:0] imgblock_2_2_V_read;
input  [9:0] imgblock_2_3_V_read;
input  [9:0] imgblock_2_4_V_read;
input  [9:0] imgblock_2_5_V_read;
input  [9:0] imgblock_2_6_V_read;
input  [9:0] imgblock_2_7_V_read;
input  [9:0] imgblock_2_8_V_read;
input  [9:0] imgblock_2_9_V_read;
input  [9:0] imgblock_3_0_V_read;
input  [9:0] imgblock_3_1_V_read;
input  [9:0] imgblock_3_2_V_read;
input  [9:0] imgblock_3_3_V_read;
input  [9:0] imgblock_3_4_V_read;
input  [9:0] imgblock_3_5_V_read;
input  [9:0] imgblock_3_6_V_read;
input  [9:0] imgblock_3_7_V_read;
input  [9:0] imgblock_3_8_V_read;
input  [9:0] imgblock_3_9_V_read;
input  [9:0] imgblock_4_0_V_read;
input  [9:0] imgblock_4_1_V_read;
input  [9:0] imgblock_4_2_V_read;
input  [9:0] imgblock_4_3_V_read;
input  [9:0] imgblock_4_4_V_read;
input  [9:0] imgblock_4_5_V_read;
input  [9:0] imgblock_4_6_V_read;
input  [9:0] imgblock_4_7_V_read;
input  [9:0] imgblock_4_8_V_read;
input  [9:0] imgblock_4_9_V_read;
input  [15:0] row;
input  [15:0] col;
input  [3:0] loop_r;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
input   ap_ce;

reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;

wire   [13:0] grp_g_kernel_fu_800_ap_return;
reg   [13:0] reg_905;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] trunc_ln123_reg_1555;
reg   [0:0] trunc_ln123_reg_1555_pp0_iter2_reg;
reg   [0:0] trunc_ln124_reg_1559;
reg   [0:0] trunc_ln124_reg_1559_pp0_iter2_reg;
wire   [13:0] grp_rgb_bgr_kernel_fu_483_ap_return;
wire   [13:0] grp_rgr_bgb_kernel_fu_588_ap_return;
wire   [0:0] trunc_ln123_fu_923_p1;
reg   [0:0] trunc_ln123_reg_1555_pp0_iter1_reg;
reg   [0:0] trunc_ln123_reg_1555_pp0_iter3_reg;
wire   [0:0] trunc_ln124_fu_927_p1;
reg   [0:0] trunc_ln124_reg_1559_pp0_iter1_reg;
reg   [0:0] trunc_ln124_reg_1559_pp0_iter3_reg;
wire   [1:0] trunc_ln129_fu_931_p1;
wire   [9:0] tmp_80_fu_953_p12;
reg   [9:0] tmp_80_reg_1571;
reg   [9:0] tmp_80_reg_1571_pp0_iter1_reg;
reg   [9:0] tmp_80_reg_1571_pp0_iter2_reg;
reg   [9:0] tmp_80_reg_1571_pp0_iter3_reg;
wire   [9:0] tmp_79_fu_993_p12;
reg   [9:0] tmp_79_reg_1576;
reg   [9:0] tmp_79_reg_1576_pp0_iter1_reg;
reg   [9:0] tmp_79_reg_1576_pp0_iter2_reg;
wire   [1:0] trunc_ln135_fu_1019_p1;
wire   [9:0] tmp_78_fu_1039_p12;
reg   [9:0] tmp_78_reg_1587;
reg   [9:0] tmp_78_reg_1587_pp0_iter1_reg;
reg   [9:0] tmp_78_reg_1587_pp0_iter2_reg;
wire   [9:0] tmp_77_fu_1079_p12;
reg   [9:0] tmp_77_reg_1592;
reg   [9:0] tmp_77_reg_1592_pp0_iter1_reg;
reg   [9:0] tmp_77_reg_1592_pp0_iter2_reg;
reg   [9:0] tmp_77_reg_1592_pp0_iter3_reg;
wire   [1:0] trunc_ln140_fu_1105_p1;
wire   [13:0] zext_ln131_fu_1111_p1;
wire   [13:0] zext_ln137_fu_1114_p1;
reg   [1:0] grp_rgb_bgr_kernel_fu_483_loop_r;
reg    grp_rgb_bgr_kernel_fu_483_ap_ce;
reg    ap_predicate_op70_call_state1;
reg    ap_predicate_op83_call_state1;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call0;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call0;
wire    ap_block_pp0_stage0_11001_ignoreCallOp70;
reg   [1:0] grp_rgr_bgb_kernel_fu_588_loop_r;
reg    grp_rgr_bgb_kernel_fu_588_ap_ce;
reg    ap_predicate_op75_call_state1;
reg    ap_predicate_op78_call_state1;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call6;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call6;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call6;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call6;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call6;
wire    ap_block_pp0_stage0_11001_ignoreCallOp75;
reg   [1:0] grp_rb_kernel_fu_693_loop_r;
wire   [13:0] grp_rb_kernel_fu_693_ap_return;
reg    grp_rb_kernel_fu_693_ap_ce;
reg    ap_predicate_op64_call_state1;
reg    ap_predicate_op90_call_state1;
wire    ap_block_pp0_stage0_11001_ignoreCallOp64;
reg   [1:0] grp_g_kernel_fu_800_loop_r;
reg    grp_g_kernel_fu_800_ap_ce;
reg    ap_predicate_op65_call_state1;
reg    ap_predicate_op89_call_state1;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call1;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call1;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call1;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call1;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call1;
wire    ap_block_pp0_stage0_11001_ignoreCallOp65;
reg   [13:0] ap_phi_mux_g_write_assign_phi_fu_447_p8;
reg   [13:0] ap_phi_reg_pp0_iter4_g_write_assign_reg_444;
wire   [13:0] ap_phi_reg_pp0_iter0_g_write_assign_reg_444;
reg   [13:0] ap_phi_reg_pp0_iter1_g_write_assign_reg_444;
reg   [13:0] ap_phi_reg_pp0_iter2_g_write_assign_reg_444;
reg   [13:0] ap_phi_reg_pp0_iter3_g_write_assign_reg_444;
reg   [13:0] ap_phi_mux_b_write_assign_phi_fu_460_p8;
reg   [13:0] ap_phi_reg_pp0_iter4_b_write_assign_reg_457;
wire   [13:0] ap_phi_reg_pp0_iter0_b_write_assign_reg_457;
reg   [13:0] ap_phi_reg_pp0_iter1_b_write_assign_reg_457;
reg   [13:0] ap_phi_reg_pp0_iter2_b_write_assign_reg_457;
reg   [13:0] ap_phi_reg_pp0_iter3_b_write_assign_reg_457;
wire   [13:0] zext_ln140_fu_1121_p1;
reg   [13:0] ap_phi_mux_r_write_assign_phi_fu_473_p8;
wire   [13:0] zext_ln128_fu_1117_p1;
reg   [13:0] ap_phi_reg_pp0_iter4_r_write_assign_reg_470;
wire   [13:0] ap_phi_reg_pp0_iter0_r_write_assign_reg_470;
reg   [13:0] ap_phi_reg_pp0_iter1_r_write_assign_reg_470;
reg   [13:0] ap_phi_reg_pp0_iter2_r_write_assign_reg_470;
reg   [13:0] ap_phi_reg_pp0_iter3_r_write_assign_reg_470;
wire    ap_block_pp0_stage0;
wire   [2:0] trunc_ln544_3_fu_939_p1;
wire   [2:0] add_ln544_fu_943_p2;
wire   [3:0] tmp_80_fu_953_p11;
wire   [2:0] trunc_ln544_2_fu_979_p1;
wire   [2:0] add_ln544_1_fu_983_p2;
wire   [3:0] tmp_79_fu_993_p11;
wire   [2:0] trunc_ln544_1_fu_1025_p1;
wire   [2:0] add_ln544_2_fu_1029_p2;
wire   [3:0] tmp_78_fu_1039_p11;
wire   [2:0] trunc_ln544_fu_1065_p1;
wire   [2:0] add_ln544_3_fu_1069_p2;
wire   [3:0] tmp_77_fu_1079_p11;
wire  signed [31:0] sext_ln121_1_fu_1129_p1;
wire  signed [31:0] sext_ln121_fu_1125_p1;
wire  signed [31:0] sext_ln121_2_fu_1133_p1;
reg    ap_ce_reg;
reg   [9:0] imgblock_0_0_V_read_int_reg;
reg   [9:0] imgblock_0_1_V_read_int_reg;
reg   [9:0] imgblock_0_2_V_read_int_reg;
reg   [9:0] imgblock_0_3_V_read_int_reg;
reg   [9:0] imgblock_0_4_V_read_int_reg;
reg   [9:0] imgblock_0_5_V_read_int_reg;
reg   [9:0] imgblock_0_6_V_read_int_reg;
reg   [9:0] imgblock_0_7_V_read_int_reg;
reg   [9:0] imgblock_0_8_V_read_int_reg;
reg   [9:0] imgblock_0_9_V_read_int_reg;
reg   [9:0] imgblock_1_0_V_read_int_reg;
reg   [9:0] imgblock_1_1_V_read_int_reg;
reg   [9:0] imgblock_1_2_V_read_int_reg;
reg   [9:0] imgblock_1_3_V_read_int_reg;
reg   [9:0] imgblock_1_4_V_read_int_reg;
reg   [9:0] imgblock_1_5_V_read_int_reg;
reg   [9:0] imgblock_1_6_V_read_int_reg;
reg   [9:0] imgblock_1_7_V_read_int_reg;
reg   [9:0] imgblock_1_8_V_read_int_reg;
reg   [9:0] imgblock_1_9_V_read_int_reg;
reg   [9:0] imgblock_2_0_V_read_int_reg;
reg   [9:0] imgblock_2_1_V_read_int_reg;
reg   [9:0] imgblock_2_2_V_read_int_reg;
reg   [9:0] imgblock_2_3_V_read_int_reg;
reg   [9:0] imgblock_2_4_V_read_int_reg;
reg   [9:0] imgblock_2_5_V_read_int_reg;
reg   [9:0] imgblock_2_6_V_read_int_reg;
reg   [9:0] imgblock_2_7_V_read_int_reg;
reg   [9:0] imgblock_2_8_V_read_int_reg;
reg   [9:0] imgblock_2_9_V_read_int_reg;
reg   [9:0] imgblock_3_0_V_read_int_reg;
reg   [9:0] imgblock_3_1_V_read_int_reg;
reg   [9:0] imgblock_3_2_V_read_int_reg;
reg   [9:0] imgblock_3_3_V_read_int_reg;
reg   [9:0] imgblock_3_4_V_read_int_reg;
reg   [9:0] imgblock_3_5_V_read_int_reg;
reg   [9:0] imgblock_3_6_V_read_int_reg;
reg   [9:0] imgblock_3_7_V_read_int_reg;
reg   [9:0] imgblock_3_8_V_read_int_reg;
reg   [9:0] imgblock_3_9_V_read_int_reg;
reg   [9:0] imgblock_4_0_V_read_int_reg;
reg   [9:0] imgblock_4_1_V_read_int_reg;
reg   [9:0] imgblock_4_2_V_read_int_reg;
reg   [9:0] imgblock_4_3_V_read_int_reg;
reg   [9:0] imgblock_4_4_V_read_int_reg;
reg   [9:0] imgblock_4_5_V_read_int_reg;
reg   [9:0] imgblock_4_6_V_read_int_reg;
reg   [9:0] imgblock_4_7_V_read_int_reg;
reg   [9:0] imgblock_4_8_V_read_int_reg;
reg   [9:0] imgblock_4_9_V_read_int_reg;
reg   [15:0] row_int_reg;
reg   [15:0] col_int_reg;
reg   [3:0] loop_r_int_reg;
reg   [31:0] ap_return_0_int_reg;
reg   [31:0] ap_return_1_int_reg;
reg   [31:0] ap_return_2_int_reg;

rgb_bgr_kernel grp_rgb_bgr_kernel_fu_483(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .imgblock_0_0_V_read(imgblock_0_0_V_read_int_reg),
    .imgblock_0_1_V_read(imgblock_0_1_V_read_int_reg),
    .imgblock_0_2_V_read(imgblock_0_2_V_read_int_reg),
    .imgblock_0_3_V_read(imgblock_0_3_V_read_int_reg),
    .imgblock_0_4_V_read(imgblock_0_4_V_read_int_reg),
    .imgblock_0_5_V_read(imgblock_0_5_V_read_int_reg),
    .imgblock_0_6_V_read(imgblock_0_6_V_read_int_reg),
    .imgblock_0_7_V_read(imgblock_0_7_V_read_int_reg),
    .imgblock_0_8_V_read(imgblock_0_8_V_read_int_reg),
    .imgblock_0_9_V_read(imgblock_0_9_V_read_int_reg),
    .imgblock_1_0_V_read(imgblock_1_0_V_read_int_reg),
    .imgblock_1_1_V_read(imgblock_1_1_V_read_int_reg),
    .imgblock_1_2_V_read(imgblock_1_2_V_read_int_reg),
    .imgblock_1_3_V_read(imgblock_1_3_V_read_int_reg),
    .imgblock_1_4_V_read(imgblock_1_4_V_read_int_reg),
    .imgblock_1_5_V_read(imgblock_1_5_V_read_int_reg),
    .imgblock_1_6_V_read(imgblock_1_6_V_read_int_reg),
    .imgblock_1_7_V_read(imgblock_1_7_V_read_int_reg),
    .imgblock_1_8_V_read(imgblock_1_8_V_read_int_reg),
    .imgblock_1_9_V_read(imgblock_1_9_V_read_int_reg),
    .imgblock_2_0_V_read(imgblock_2_0_V_read_int_reg),
    .imgblock_2_1_V_read(imgblock_2_1_V_read_int_reg),
    .imgblock_2_2_V_read(imgblock_2_2_V_read_int_reg),
    .imgblock_2_3_V_read(imgblock_2_3_V_read_int_reg),
    .imgblock_2_4_V_read(imgblock_2_4_V_read_int_reg),
    .imgblock_2_5_V_read(imgblock_2_5_V_read_int_reg),
    .imgblock_2_6_V_read(imgblock_2_6_V_read_int_reg),
    .imgblock_2_7_V_read(imgblock_2_7_V_read_int_reg),
    .imgblock_2_8_V_read(imgblock_2_8_V_read_int_reg),
    .imgblock_2_9_V_read(imgblock_2_9_V_read_int_reg),
    .imgblock_3_0_V_read(imgblock_3_0_V_read_int_reg),
    .imgblock_3_1_V_read(imgblock_3_1_V_read_int_reg),
    .imgblock_3_2_V_read(imgblock_3_2_V_read_int_reg),
    .imgblock_3_3_V_read(imgblock_3_3_V_read_int_reg),
    .imgblock_3_4_V_read(imgblock_3_4_V_read_int_reg),
    .imgblock_3_5_V_read(imgblock_3_5_V_read_int_reg),
    .imgblock_3_6_V_read(imgblock_3_6_V_read_int_reg),
    .imgblock_3_7_V_read(imgblock_3_7_V_read_int_reg),
    .imgblock_3_8_V_read(imgblock_3_8_V_read_int_reg),
    .imgblock_3_9_V_read(imgblock_3_9_V_read_int_reg),
    .imgblock_4_0_V_read(imgblock_4_0_V_read_int_reg),
    .imgblock_4_1_V_read(imgblock_4_1_V_read_int_reg),
    .imgblock_4_2_V_read(imgblock_4_2_V_read_int_reg),
    .imgblock_4_3_V_read(imgblock_4_3_V_read_int_reg),
    .imgblock_4_4_V_read(imgblock_4_4_V_read_int_reg),
    .imgblock_4_5_V_read(imgblock_4_5_V_read_int_reg),
    .imgblock_4_6_V_read(imgblock_4_6_V_read_int_reg),
    .imgblock_4_7_V_read(imgblock_4_7_V_read_int_reg),
    .imgblock_4_8_V_read(imgblock_4_8_V_read_int_reg),
    .imgblock_4_9_V_read(imgblock_4_9_V_read_int_reg),
    .loop_r(grp_rgb_bgr_kernel_fu_483_loop_r),
    .ap_return(grp_rgb_bgr_kernel_fu_483_ap_return),
    .ap_ce(grp_rgb_bgr_kernel_fu_483_ap_ce)
);

rgr_bgb_kernel grp_rgr_bgb_kernel_fu_588(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .imgblock_0_0_V_read(imgblock_0_0_V_read_int_reg),
    .imgblock_0_1_V_read(imgblock_0_1_V_read_int_reg),
    .imgblock_0_2_V_read(imgblock_0_2_V_read_int_reg),
    .imgblock_0_3_V_read(imgblock_0_3_V_read_int_reg),
    .imgblock_0_4_V_read(imgblock_0_4_V_read_int_reg),
    .imgblock_0_5_V_read(imgblock_0_5_V_read_int_reg),
    .imgblock_0_6_V_read(imgblock_0_6_V_read_int_reg),
    .imgblock_0_7_V_read(imgblock_0_7_V_read_int_reg),
    .imgblock_0_8_V_read(imgblock_0_8_V_read_int_reg),
    .imgblock_0_9_V_read(imgblock_0_9_V_read_int_reg),
    .imgblock_1_0_V_read(imgblock_1_0_V_read_int_reg),
    .imgblock_1_1_V_read(imgblock_1_1_V_read_int_reg),
    .imgblock_1_2_V_read(imgblock_1_2_V_read_int_reg),
    .imgblock_1_3_V_read(imgblock_1_3_V_read_int_reg),
    .imgblock_1_4_V_read(imgblock_1_4_V_read_int_reg),
    .imgblock_1_5_V_read(imgblock_1_5_V_read_int_reg),
    .imgblock_1_6_V_read(imgblock_1_6_V_read_int_reg),
    .imgblock_1_7_V_read(imgblock_1_7_V_read_int_reg),
    .imgblock_1_8_V_read(imgblock_1_8_V_read_int_reg),
    .imgblock_1_9_V_read(imgblock_1_9_V_read_int_reg),
    .imgblock_2_0_V_read(imgblock_2_0_V_read_int_reg),
    .imgblock_2_1_V_read(imgblock_2_1_V_read_int_reg),
    .imgblock_2_2_V_read(imgblock_2_2_V_read_int_reg),
    .imgblock_2_3_V_read(imgblock_2_3_V_read_int_reg),
    .imgblock_2_4_V_read(imgblock_2_4_V_read_int_reg),
    .imgblock_2_5_V_read(imgblock_2_5_V_read_int_reg),
    .imgblock_2_6_V_read(imgblock_2_6_V_read_int_reg),
    .imgblock_2_7_V_read(imgblock_2_7_V_read_int_reg),
    .imgblock_2_8_V_read(imgblock_2_8_V_read_int_reg),
    .imgblock_2_9_V_read(imgblock_2_9_V_read_int_reg),
    .imgblock_3_0_V_read(imgblock_3_0_V_read_int_reg),
    .imgblock_3_1_V_read(imgblock_3_1_V_read_int_reg),
    .imgblock_3_2_V_read(imgblock_3_2_V_read_int_reg),
    .imgblock_3_3_V_read(imgblock_3_3_V_read_int_reg),
    .imgblock_3_4_V_read(imgblock_3_4_V_read_int_reg),
    .imgblock_3_5_V_read(imgblock_3_5_V_read_int_reg),
    .imgblock_3_6_V_read(imgblock_3_6_V_read_int_reg),
    .imgblock_3_7_V_read(imgblock_3_7_V_read_int_reg),
    .imgblock_3_8_V_read(imgblock_3_8_V_read_int_reg),
    .imgblock_3_9_V_read(imgblock_3_9_V_read_int_reg),
    .imgblock_4_0_V_read(imgblock_4_0_V_read_int_reg),
    .imgblock_4_1_V_read(imgblock_4_1_V_read_int_reg),
    .imgblock_4_2_V_read(imgblock_4_2_V_read_int_reg),
    .imgblock_4_3_V_read(imgblock_4_3_V_read_int_reg),
    .imgblock_4_4_V_read(imgblock_4_4_V_read_int_reg),
    .imgblock_4_5_V_read(imgblock_4_5_V_read_int_reg),
    .imgblock_4_6_V_read(imgblock_4_6_V_read_int_reg),
    .imgblock_4_7_V_read(imgblock_4_7_V_read_int_reg),
    .imgblock_4_8_V_read(imgblock_4_8_V_read_int_reg),
    .imgblock_4_9_V_read(imgblock_4_9_V_read_int_reg),
    .loop_r(grp_rgr_bgb_kernel_fu_588_loop_r),
    .ap_return(grp_rgr_bgb_kernel_fu_588_ap_return),
    .ap_ce(grp_rgr_bgb_kernel_fu_588_ap_ce)
);

rb_kernel grp_rb_kernel_fu_693(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .imgblock_0_0_V_read(imgblock_0_0_V_read_int_reg),
    .imgblock_0_1_V_read(imgblock_0_1_V_read_int_reg),
    .imgblock_0_2_V_read(imgblock_0_2_V_read_int_reg),
    .imgblock_0_3_V_read(imgblock_0_3_V_read_int_reg),
    .imgblock_0_4_V_read(imgblock_0_4_V_read_int_reg),
    .imgblock_0_5_V_read(imgblock_0_5_V_read_int_reg),
    .imgblock_0_6_V_read(imgblock_0_6_V_read_int_reg),
    .imgblock_0_7_V_read(imgblock_0_7_V_read_int_reg),
    .imgblock_0_8_V_read(imgblock_0_8_V_read_int_reg),
    .imgblock_0_9_V_read(imgblock_0_9_V_read_int_reg),
    .imgblock_1_0_V_read(imgblock_1_0_V_read_int_reg),
    .imgblock_1_1_V_read(imgblock_1_1_V_read_int_reg),
    .imgblock_1_2_V_read(imgblock_1_2_V_read_int_reg),
    .imgblock_1_3_V_read(imgblock_1_3_V_read_int_reg),
    .imgblock_1_4_V_read(imgblock_1_4_V_read_int_reg),
    .imgblock_1_5_V_read(imgblock_1_5_V_read_int_reg),
    .imgblock_1_6_V_read(imgblock_1_6_V_read_int_reg),
    .imgblock_1_7_V_read(imgblock_1_7_V_read_int_reg),
    .imgblock_1_8_V_read(imgblock_1_8_V_read_int_reg),
    .imgblock_1_9_V_read(imgblock_1_9_V_read_int_reg),
    .imgblock_2_0_V_read(imgblock_2_0_V_read_int_reg),
    .imgblock_2_1_V_read(imgblock_2_1_V_read_int_reg),
    .imgblock_2_2_V_read(imgblock_2_2_V_read_int_reg),
    .imgblock_2_3_V_read(imgblock_2_3_V_read_int_reg),
    .imgblock_2_4_V_read(imgblock_2_4_V_read_int_reg),
    .imgblock_2_5_V_read(imgblock_2_5_V_read_int_reg),
    .imgblock_2_6_V_read(imgblock_2_6_V_read_int_reg),
    .imgblock_2_7_V_read(imgblock_2_7_V_read_int_reg),
    .imgblock_2_8_V_read(imgblock_2_8_V_read_int_reg),
    .imgblock_2_9_V_read(imgblock_2_9_V_read_int_reg),
    .imgblock_3_0_V_read(imgblock_3_0_V_read_int_reg),
    .imgblock_3_1_V_read(imgblock_3_1_V_read_int_reg),
    .imgblock_3_2_V_read(imgblock_3_2_V_read_int_reg),
    .imgblock_3_3_V_read(imgblock_3_3_V_read_int_reg),
    .imgblock_3_4_V_read(imgblock_3_4_V_read_int_reg),
    .imgblock_3_5_V_read(imgblock_3_5_V_read_int_reg),
    .imgblock_3_6_V_read(imgblock_3_6_V_read_int_reg),
    .imgblock_3_7_V_read(imgblock_3_7_V_read_int_reg),
    .imgblock_3_8_V_read(imgblock_3_8_V_read_int_reg),
    .imgblock_3_9_V_read(imgblock_3_9_V_read_int_reg),
    .imgblock_4_0_V_read(imgblock_4_0_V_read_int_reg),
    .imgblock_4_1_V_read(imgblock_4_1_V_read_int_reg),
    .imgblock_4_2_V_read(imgblock_4_2_V_read_int_reg),
    .imgblock_4_3_V_read(imgblock_4_3_V_read_int_reg),
    .imgblock_4_4_V_read(imgblock_4_4_V_read_int_reg),
    .imgblock_4_5_V_read(imgblock_4_5_V_read_int_reg),
    .imgblock_4_6_V_read(imgblock_4_6_V_read_int_reg),
    .imgblock_4_7_V_read(imgblock_4_7_V_read_int_reg),
    .imgblock_4_8_V_read(imgblock_4_8_V_read_int_reg),
    .imgblock_4_9_V_read(imgblock_4_9_V_read_int_reg),
    .loop_r(grp_rb_kernel_fu_693_loop_r),
    .ap_return(grp_rb_kernel_fu_693_ap_return),
    .ap_ce(grp_rb_kernel_fu_693_ap_ce)
);

g_kernel grp_g_kernel_fu_800(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .imgblock_0_0_V_read(imgblock_0_0_V_read_int_reg),
    .imgblock_0_1_V_read(imgblock_0_1_V_read_int_reg),
    .imgblock_0_2_V_read(imgblock_0_2_V_read_int_reg),
    .imgblock_0_3_V_read(imgblock_0_3_V_read_int_reg),
    .imgblock_0_4_V_read(imgblock_0_4_V_read_int_reg),
    .imgblock_0_5_V_read(imgblock_0_5_V_read_int_reg),
    .imgblock_0_6_V_read(imgblock_0_6_V_read_int_reg),
    .imgblock_0_7_V_read(imgblock_0_7_V_read_int_reg),
    .imgblock_0_8_V_read(imgblock_0_8_V_read_int_reg),
    .imgblock_0_9_V_read(imgblock_0_9_V_read_int_reg),
    .imgblock_1_0_V_read(imgblock_1_0_V_read_int_reg),
    .imgblock_1_1_V_read(imgblock_1_1_V_read_int_reg),
    .imgblock_1_2_V_read(imgblock_1_2_V_read_int_reg),
    .imgblock_1_3_V_read(imgblock_1_3_V_read_int_reg),
    .imgblock_1_4_V_read(imgblock_1_4_V_read_int_reg),
    .imgblock_1_5_V_read(imgblock_1_5_V_read_int_reg),
    .imgblock_1_6_V_read(imgblock_1_6_V_read_int_reg),
    .imgblock_1_7_V_read(imgblock_1_7_V_read_int_reg),
    .imgblock_1_8_V_read(imgblock_1_8_V_read_int_reg),
    .imgblock_1_9_V_read(imgblock_1_9_V_read_int_reg),
    .imgblock_2_0_V_read(imgblock_2_0_V_read_int_reg),
    .imgblock_2_1_V_read(imgblock_2_1_V_read_int_reg),
    .imgblock_2_2_V_read(imgblock_2_2_V_read_int_reg),
    .imgblock_2_3_V_read(imgblock_2_3_V_read_int_reg),
    .imgblock_2_4_V_read(imgblock_2_4_V_read_int_reg),
    .imgblock_2_5_V_read(imgblock_2_5_V_read_int_reg),
    .imgblock_2_6_V_read(imgblock_2_6_V_read_int_reg),
    .imgblock_2_7_V_read(imgblock_2_7_V_read_int_reg),
    .imgblock_2_8_V_read(imgblock_2_8_V_read_int_reg),
    .imgblock_2_9_V_read(imgblock_2_9_V_read_int_reg),
    .imgblock_3_0_V_read(imgblock_3_0_V_read_int_reg),
    .imgblock_3_1_V_read(imgblock_3_1_V_read_int_reg),
    .imgblock_3_2_V_read(imgblock_3_2_V_read_int_reg),
    .imgblock_3_3_V_read(imgblock_3_3_V_read_int_reg),
    .imgblock_3_4_V_read(imgblock_3_4_V_read_int_reg),
    .imgblock_3_5_V_read(imgblock_3_5_V_read_int_reg),
    .imgblock_3_6_V_read(imgblock_3_6_V_read_int_reg),
    .imgblock_3_7_V_read(imgblock_3_7_V_read_int_reg),
    .imgblock_3_8_V_read(imgblock_3_8_V_read_int_reg),
    .imgblock_3_9_V_read(imgblock_3_9_V_read_int_reg),
    .imgblock_4_0_V_read(imgblock_4_0_V_read_int_reg),
    .imgblock_4_1_V_read(imgblock_4_1_V_read_int_reg),
    .imgblock_4_2_V_read(imgblock_4_2_V_read_int_reg),
    .imgblock_4_3_V_read(imgblock_4_3_V_read_int_reg),
    .imgblock_4_4_V_read(imgblock_4_4_V_read_int_reg),
    .imgblock_4_5_V_read(imgblock_4_5_V_read_int_reg),
    .imgblock_4_6_V_read(imgblock_4_6_V_read_int_reg),
    .imgblock_4_7_V_read(imgblock_4_7_V_read_int_reg),
    .imgblock_4_8_V_read(imgblock_4_8_V_read_int_reg),
    .imgblock_4_9_V_read(imgblock_4_9_V_read_int_reg),
    .loop_r(grp_g_kernel_fu_800_loop_r),
    .ap_return(grp_g_kernel_fu_800_ap_return),
    .ap_ce(grp_g_kernel_fu_800_ap_ce)
);

ISPPipeline_accelkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
ISPPipeline_accelkbM_U347(
    .din0(imgblock_2_0_V_read_int_reg),
    .din1(imgblock_2_1_V_read_int_reg),
    .din2(imgblock_2_2_V_read_int_reg),
    .din3(imgblock_2_3_V_read_int_reg),
    .din4(imgblock_2_4_V_read_int_reg),
    .din5(imgblock_2_5_V_read_int_reg),
    .din6(imgblock_2_6_V_read_int_reg),
    .din7(imgblock_2_7_V_read_int_reg),
    .din8(imgblock_2_8_V_read_int_reg),
    .din9(imgblock_2_9_V_read_int_reg),
    .din10(tmp_80_fu_953_p11),
    .dout(tmp_80_fu_953_p12)
);

ISPPipeline_accelkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
ISPPipeline_accelkbM_U348(
    .din0(imgblock_2_0_V_read_int_reg),
    .din1(imgblock_2_1_V_read_int_reg),
    .din2(imgblock_2_2_V_read_int_reg),
    .din3(imgblock_2_3_V_read_int_reg),
    .din4(imgblock_2_4_V_read_int_reg),
    .din5(imgblock_2_5_V_read_int_reg),
    .din6(imgblock_2_6_V_read_int_reg),
    .din7(imgblock_2_7_V_read_int_reg),
    .din8(imgblock_2_8_V_read_int_reg),
    .din9(imgblock_2_9_V_read_int_reg),
    .din10(tmp_79_fu_993_p11),
    .dout(tmp_79_fu_993_p12)
);

ISPPipeline_accelkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
ISPPipeline_accelkbM_U349(
    .din0(imgblock_2_0_V_read_int_reg),
    .din1(imgblock_2_1_V_read_int_reg),
    .din2(imgblock_2_2_V_read_int_reg),
    .din3(imgblock_2_3_V_read_int_reg),
    .din4(imgblock_2_4_V_read_int_reg),
    .din5(imgblock_2_5_V_read_int_reg),
    .din6(imgblock_2_6_V_read_int_reg),
    .din7(imgblock_2_7_V_read_int_reg),
    .din8(imgblock_2_8_V_read_int_reg),
    .din9(imgblock_2_9_V_read_int_reg),
    .din10(tmp_78_fu_1039_p11),
    .dout(tmp_78_fu_1039_p12)
);

ISPPipeline_accelkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 10 ),
    .din5_WIDTH( 10 ),
    .din6_WIDTH( 10 ),
    .din7_WIDTH( 10 ),
    .din8_WIDTH( 10 ),
    .din9_WIDTH( 10 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 10 ))
ISPPipeline_accelkbM_U350(
    .din0(imgblock_2_0_V_read_int_reg),
    .din1(imgblock_2_1_V_read_int_reg),
    .din2(imgblock_2_2_V_read_int_reg),
    .din3(imgblock_2_3_V_read_int_reg),
    .din4(imgblock_2_4_V_read_int_reg),
    .din5(imgblock_2_5_V_read_int_reg),
    .din6(imgblock_2_6_V_read_int_reg),
    .din7(imgblock_2_7_V_read_int_reg),
    .din8(imgblock_2_8_V_read_int_reg),
    .din9(imgblock_2_9_V_read_int_reg),
    .din10(tmp_77_fu_1079_p11),
    .dout(tmp_77_fu_1079_p12)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_b_write_assign_reg_457 <= grp_rgr_bgb_kernel_fu_588_ap_return;
        end else if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_b_write_assign_reg_457 <= grp_rgb_bgr_kernel_fu_483_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_b_write_assign_reg_457 <= ap_phi_reg_pp0_iter3_b_write_assign_reg_457;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_g_write_assign_reg_444 <= zext_ln137_fu_1114_p1;
        end else if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_g_write_assign_reg_444 <= zext_ln131_fu_1111_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_g_write_assign_reg_444 <= ap_phi_reg_pp0_iter3_g_write_assign_reg_444;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd1))) begin
            ap_phi_reg_pp0_iter4_r_write_assign_reg_470 <= grp_rgb_bgr_kernel_fu_483_ap_return;
        end else if (((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd0))) begin
            ap_phi_reg_pp0_iter4_r_write_assign_reg_470 <= grp_rgr_bgb_kernel_fu_588_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_r_write_assign_reg_470 <= ap_phi_reg_pp0_iter3_r_write_assign_reg_470;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        ap_phi_reg_pp0_iter1_b_write_assign_reg_457 <= ap_phi_reg_pp0_iter0_b_write_assign_reg_457;
        ap_phi_reg_pp0_iter1_g_write_assign_reg_444 <= ap_phi_reg_pp0_iter0_g_write_assign_reg_444;
        ap_phi_reg_pp0_iter1_r_write_assign_reg_470 <= ap_phi_reg_pp0_iter0_r_write_assign_reg_470;
        ap_phi_reg_pp0_iter2_b_write_assign_reg_457 <= ap_phi_reg_pp0_iter1_b_write_assign_reg_457;
        ap_phi_reg_pp0_iter2_g_write_assign_reg_444 <= ap_phi_reg_pp0_iter1_g_write_assign_reg_444;
        ap_phi_reg_pp0_iter2_r_write_assign_reg_470 <= ap_phi_reg_pp0_iter1_r_write_assign_reg_470;
        ap_phi_reg_pp0_iter3_b_write_assign_reg_457 <= ap_phi_reg_pp0_iter2_b_write_assign_reg_457;
        ap_phi_reg_pp0_iter3_g_write_assign_reg_444 <= ap_phi_reg_pp0_iter2_g_write_assign_reg_444;
        ap_phi_reg_pp0_iter3_r_write_assign_reg_470 <= ap_phi_reg_pp0_iter2_r_write_assign_reg_470;
        tmp_77_reg_1592_pp0_iter1_reg <= tmp_77_reg_1592;
        tmp_77_reg_1592_pp0_iter2_reg <= tmp_77_reg_1592_pp0_iter1_reg;
        tmp_77_reg_1592_pp0_iter3_reg <= tmp_77_reg_1592_pp0_iter2_reg;
        tmp_78_reg_1587_pp0_iter1_reg <= tmp_78_reg_1587;
        tmp_78_reg_1587_pp0_iter2_reg <= tmp_78_reg_1587_pp0_iter1_reg;
        tmp_79_reg_1576_pp0_iter1_reg <= tmp_79_reg_1576;
        tmp_79_reg_1576_pp0_iter2_reg <= tmp_79_reg_1576_pp0_iter1_reg;
        tmp_80_reg_1571_pp0_iter1_reg <= tmp_80_reg_1571;
        tmp_80_reg_1571_pp0_iter2_reg <= tmp_80_reg_1571_pp0_iter1_reg;
        tmp_80_reg_1571_pp0_iter3_reg <= tmp_80_reg_1571_pp0_iter2_reg;
        trunc_ln123_reg_1555 <= trunc_ln123_fu_923_p1;
        trunc_ln123_reg_1555_pp0_iter1_reg <= trunc_ln123_reg_1555;
        trunc_ln123_reg_1555_pp0_iter2_reg <= trunc_ln123_reg_1555_pp0_iter1_reg;
        trunc_ln123_reg_1555_pp0_iter3_reg <= trunc_ln123_reg_1555_pp0_iter2_reg;
        trunc_ln124_reg_1559 <= trunc_ln124_fu_927_p1;
        trunc_ln124_reg_1559_pp0_iter1_reg <= trunc_ln124_reg_1559;
        trunc_ln124_reg_1559_pp0_iter2_reg <= trunc_ln124_reg_1559_pp0_iter1_reg;
        trunc_ln124_reg_1559_pp0_iter3_reg <= trunc_ln124_reg_1559_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= sext_ln121_1_fu_1129_p1;
        ap_return_1_int_reg <= sext_ln121_fu_1125_p1;
        ap_return_2_int_reg <= sext_ln121_2_fu_1133_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        col_int_reg <= col;
        imgblock_0_0_V_read_int_reg <= imgblock_0_0_V_read;
        imgblock_0_1_V_read_int_reg <= imgblock_0_1_V_read;
        imgblock_0_2_V_read_int_reg <= imgblock_0_2_V_read;
        imgblock_0_3_V_read_int_reg <= imgblock_0_3_V_read;
        imgblock_0_4_V_read_int_reg <= imgblock_0_4_V_read;
        imgblock_0_5_V_read_int_reg <= imgblock_0_5_V_read;
        imgblock_0_6_V_read_int_reg <= imgblock_0_6_V_read;
        imgblock_0_7_V_read_int_reg <= imgblock_0_7_V_read;
        imgblock_0_8_V_read_int_reg <= imgblock_0_8_V_read;
        imgblock_0_9_V_read_int_reg <= imgblock_0_9_V_read;
        imgblock_1_0_V_read_int_reg <= imgblock_1_0_V_read;
        imgblock_1_1_V_read_int_reg <= imgblock_1_1_V_read;
        imgblock_1_2_V_read_int_reg <= imgblock_1_2_V_read;
        imgblock_1_3_V_read_int_reg <= imgblock_1_3_V_read;
        imgblock_1_4_V_read_int_reg <= imgblock_1_4_V_read;
        imgblock_1_5_V_read_int_reg <= imgblock_1_5_V_read;
        imgblock_1_6_V_read_int_reg <= imgblock_1_6_V_read;
        imgblock_1_7_V_read_int_reg <= imgblock_1_7_V_read;
        imgblock_1_8_V_read_int_reg <= imgblock_1_8_V_read;
        imgblock_1_9_V_read_int_reg <= imgblock_1_9_V_read;
        imgblock_2_0_V_read_int_reg <= imgblock_2_0_V_read;
        imgblock_2_1_V_read_int_reg <= imgblock_2_1_V_read;
        imgblock_2_2_V_read_int_reg <= imgblock_2_2_V_read;
        imgblock_2_3_V_read_int_reg <= imgblock_2_3_V_read;
        imgblock_2_4_V_read_int_reg <= imgblock_2_4_V_read;
        imgblock_2_5_V_read_int_reg <= imgblock_2_5_V_read;
        imgblock_2_6_V_read_int_reg <= imgblock_2_6_V_read;
        imgblock_2_7_V_read_int_reg <= imgblock_2_7_V_read;
        imgblock_2_8_V_read_int_reg <= imgblock_2_8_V_read;
        imgblock_2_9_V_read_int_reg <= imgblock_2_9_V_read;
        imgblock_3_0_V_read_int_reg <= imgblock_3_0_V_read;
        imgblock_3_1_V_read_int_reg <= imgblock_3_1_V_read;
        imgblock_3_2_V_read_int_reg <= imgblock_3_2_V_read;
        imgblock_3_3_V_read_int_reg <= imgblock_3_3_V_read;
        imgblock_3_4_V_read_int_reg <= imgblock_3_4_V_read;
        imgblock_3_5_V_read_int_reg <= imgblock_3_5_V_read;
        imgblock_3_6_V_read_int_reg <= imgblock_3_6_V_read;
        imgblock_3_7_V_read_int_reg <= imgblock_3_7_V_read;
        imgblock_3_8_V_read_int_reg <= imgblock_3_8_V_read;
        imgblock_3_9_V_read_int_reg <= imgblock_3_9_V_read;
        imgblock_4_0_V_read_int_reg <= imgblock_4_0_V_read;
        imgblock_4_1_V_read_int_reg <= imgblock_4_1_V_read;
        imgblock_4_2_V_read_int_reg <= imgblock_4_2_V_read;
        imgblock_4_3_V_read_int_reg <= imgblock_4_3_V_read;
        imgblock_4_4_V_read_int_reg <= imgblock_4_4_V_read;
        imgblock_4_5_V_read_int_reg <= imgblock_4_5_V_read;
        imgblock_4_6_V_read_int_reg <= imgblock_4_6_V_read;
        imgblock_4_7_V_read_int_reg <= imgblock_4_7_V_read;
        imgblock_4_8_V_read_int_reg <= imgblock_4_8_V_read;
        imgblock_4_9_V_read_int_reg <= imgblock_4_9_V_read;
        loop_r_int_reg <= loop_r;
        row_int_reg <= row;
    end
end

always @ (posedge ap_clk) begin
    if ((((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg)) | ((trunc_ln124_reg_1559_pp0_iter2_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg)))) begin
        reg_905 <= grp_g_kernel_fu_800_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        tmp_77_reg_1592 <= tmp_77_fu_1079_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln123_fu_923_p1 == 1'd1) & (trunc_ln124_fu_927_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        tmp_78_reg_1587 <= tmp_78_fu_1039_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        tmp_79_reg_1576 <= tmp_79_fu_993_p12;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln124_fu_927_p1 == 1'd0) & (trunc_ln123_fu_923_p1 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        tmp_80_reg_1571 <= tmp_80_fu_953_p12;
    end
end

always @ (*) begin
    if (((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd1))) begin
        ap_phi_mux_b_write_assign_phi_fu_460_p8 = zext_ln140_fu_1121_p1;
    end else if (((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd0))) begin
        ap_phi_mux_b_write_assign_phi_fu_460_p8 = grp_rb_kernel_fu_693_ap_return;
    end else begin
        ap_phi_mux_b_write_assign_phi_fu_460_p8 = ap_phi_reg_pp0_iter4_b_write_assign_reg_457;
    end
end

always @ (*) begin
    if ((((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd1)) | ((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd0)))) begin
        ap_phi_mux_g_write_assign_phi_fu_447_p8 = reg_905;
    end else begin
        ap_phi_mux_g_write_assign_phi_fu_447_p8 = ap_phi_reg_pp0_iter4_g_write_assign_reg_444;
    end
end

always @ (*) begin
    if (((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd1) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd1))) begin
        ap_phi_mux_r_write_assign_phi_fu_473_p8 = grp_rb_kernel_fu_693_ap_return;
    end else if (((trunc_ln124_reg_1559_pp0_iter3_reg == 1'd0) & (trunc_ln123_reg_1555_pp0_iter3_reg == 1'd0))) begin
        ap_phi_mux_r_write_assign_phi_fu_473_p8 = zext_ln128_fu_1117_p1;
    end else begin
        ap_phi_mux_r_write_assign_phi_fu_473_p8 = ap_phi_reg_pp0_iter4_r_write_assign_reg_470;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = sext_ln121_1_fu_1129_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = sext_ln121_fu_1125_p1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = sext_ln121_2_fu_1133_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp65) & (1'b1 == ap_ce_reg))) begin
        grp_g_kernel_fu_800_ap_ce = 1'b1;
    end else begin
        grp_g_kernel_fu_800_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op89_call_state1 == 1'b1)) begin
            grp_g_kernel_fu_800_loop_r = trunc_ln140_fu_1105_p1;
        end else if ((ap_predicate_op65_call_state1 == 1'b1)) begin
            grp_g_kernel_fu_800_loop_r = trunc_ln129_fu_931_p1;
        end else begin
            grp_g_kernel_fu_800_loop_r = 'bx;
        end
    end else begin
        grp_g_kernel_fu_800_loop_r = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp64) & (1'b1 == ap_ce_reg))) begin
        grp_rb_kernel_fu_693_ap_ce = 1'b1;
    end else begin
        grp_rb_kernel_fu_693_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op90_call_state1 == 1'b1)) begin
            grp_rb_kernel_fu_693_loop_r = trunc_ln140_fu_1105_p1;
        end else if ((ap_predicate_op64_call_state1 == 1'b1)) begin
            grp_rb_kernel_fu_693_loop_r = trunc_ln129_fu_931_p1;
        end else begin
            grp_rb_kernel_fu_693_loop_r = 'bx;
        end
    end else begin
        grp_rb_kernel_fu_693_loop_r = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp70) & (1'b1 == ap_ce_reg))) begin
        grp_rgb_bgr_kernel_fu_483_ap_ce = 1'b1;
    end else begin
        grp_rgb_bgr_kernel_fu_483_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op83_call_state1 == 1'b1)) begin
            grp_rgb_bgr_kernel_fu_483_loop_r = trunc_ln135_fu_1019_p1;
        end else if ((ap_predicate_op70_call_state1 == 1'b1)) begin
            grp_rgb_bgr_kernel_fu_483_loop_r = trunc_ln129_fu_931_p1;
        end else begin
            grp_rgb_bgr_kernel_fu_483_loop_r = 'bx;
        end
    end else begin
        grp_rgb_bgr_kernel_fu_483_loop_r = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp75) & (1'b1 == ap_ce_reg))) begin
        grp_rgr_bgb_kernel_fu_588_ap_ce = 1'b1;
    end else begin
        grp_rgr_bgb_kernel_fu_588_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op78_call_state1 == 1'b1)) begin
            grp_rgr_bgb_kernel_fu_588_loop_r = trunc_ln135_fu_1019_p1;
        end else if ((ap_predicate_op75_call_state1 == 1'b1)) begin
            grp_rgr_bgb_kernel_fu_588_loop_r = trunc_ln129_fu_931_p1;
        end else begin
            grp_rgr_bgb_kernel_fu_588_loop_r = 'bx;
        end
    end else begin
        grp_rgr_bgb_kernel_fu_588_loop_r = 'bx;
    end
end

assign add_ln544_1_fu_983_p2 = (3'd2 + trunc_ln544_2_fu_979_p1);

assign add_ln544_2_fu_1029_p2 = (3'd2 + trunc_ln544_1_fu_1025_p1);

assign add_ln544_3_fu_1069_p2 = (3'd2 + trunc_ln544_fu_1065_p1);

assign add_ln544_fu_943_p2 = (3'd2 + trunc_ln544_3_fu_939_p1);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp64 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp65 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp70 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp75 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call6 = ~(1'b1 == 1'b1);

assign ap_phi_reg_pp0_iter0_b_write_assign_reg_457 = 'bx;

assign ap_phi_reg_pp0_iter0_g_write_assign_reg_444 = 'bx;

assign ap_phi_reg_pp0_iter0_r_write_assign_reg_470 = 'bx;

always @ (*) begin
    ap_predicate_op64_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd0) & (trunc_ln123_fu_923_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op65_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd0) & (trunc_ln123_fu_923_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op70_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op75_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op78_call_state1 = ((trunc_ln123_fu_923_p1 == 1'd1) & (trunc_ln124_fu_927_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op83_call_state1 = ((trunc_ln123_fu_923_p1 == 1'd1) & (trunc_ln124_fu_927_p1 == 1'd0));
end

always @ (*) begin
    ap_predicate_op89_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd1));
end

always @ (*) begin
    ap_predicate_op90_call_state1 = ((trunc_ln124_fu_927_p1 == 1'd1) & (trunc_ln123_fu_923_p1 == 1'd1));
end

assign sext_ln121_1_fu_1129_p1 = $signed(ap_phi_mux_b_write_assign_phi_fu_460_p8);

assign sext_ln121_2_fu_1133_p1 = $signed(ap_phi_mux_r_write_assign_phi_fu_473_p8);

assign sext_ln121_fu_1125_p1 = $signed(ap_phi_mux_g_write_assign_phi_fu_447_p8);

assign tmp_77_fu_1079_p11 = add_ln544_3_fu_1069_p2;

assign tmp_78_fu_1039_p11 = add_ln544_2_fu_1029_p2;

assign tmp_79_fu_993_p11 = add_ln544_1_fu_983_p2;

assign tmp_80_fu_953_p11 = add_ln544_fu_943_p2;

assign trunc_ln123_fu_923_p1 = row_int_reg[0:0];

assign trunc_ln124_fu_927_p1 = col_int_reg[0:0];

assign trunc_ln129_fu_931_p1 = loop_r_int_reg[1:0];

assign trunc_ln135_fu_1019_p1 = loop_r_int_reg[1:0];

assign trunc_ln140_fu_1105_p1 = loop_r_int_reg[1:0];

assign trunc_ln544_1_fu_1025_p1 = loop_r_int_reg[2:0];

assign trunc_ln544_2_fu_979_p1 = loop_r_int_reg[2:0];

assign trunc_ln544_3_fu_939_p1 = loop_r_int_reg[2:0];

assign trunc_ln544_fu_1065_p1 = loop_r_int_reg[2:0];

assign zext_ln128_fu_1117_p1 = tmp_80_reg_1571_pp0_iter3_reg;

assign zext_ln131_fu_1111_p1 = tmp_79_reg_1576_pp0_iter2_reg;

assign zext_ln137_fu_1114_p1 = tmp_78_reg_1587_pp0_iter2_reg;

assign zext_ln140_fu_1121_p1 = tmp_77_reg_1592_pp0_iter3_reg;

endmodule //Core_Process
