name: vitis-ai-tensorflow

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.6
  - vai_wego_tensorflow
  - vart
  - vaic
  - dpuv3-pycompiler
  - xnnc
  - xcompiler
  - pyyaml
  - jupyter
  - ipywidgets
  - dill
  - progressbar2
  - pytest
  - scikit-learn
  - pandas
  - matplotlib
